### PR TITLE
[script] Cleanup / add ntp / fix issue #90

### PR DESCRIPTION
**Pull request by hawkeyexp**
- Run rpi-update during build
- Ntp is needed to make sure rpi-update will work cause correct set time is needed for download
  Run service it only in dev mode

### CODE REVIEW

**Comment by htruong** [comment]
@hawkeyexp Thanks for spending so much time to read and tease out what was going on.

The only comment I have is that `rpi-update` is kind of a last-resort solution. If we ever need to build any DKMS/kernel module that needs the headers to compile, going for a standard kernel that comes with raspbian is so much less hassle compared to the latest git kernel -- we would need to download the whole Linux tree when we use the latest git kernel with `rpi-source` (or something like that).

So we shouldn't do it unless we absolutely need it to be done.

**Comment by hawkeyexp** [comment]
Ok thats correct but you remember i had the start problem before i have tried rpi-update and after it all worked fine. Additional it is executed on the destination-system (crankshaft image) which won't be used to build anything so it should be ok.

**Comment by htruong** [comment]
> Additional it is executed on the destination-system (crankshaft image) which won't be used to build anything so it should be ok.

That's the point I want to touch, because if we do `rpi-update` on the destination system image, that means the end-user who wants a custom DKMS module installed (when they install a DAC, for example) will have a very hard time doing so. They  will have to download `rpi-source` and wait 1 hour for the whole process to finish instead of just having to do `apt install dkms raspberrypi-kernel-headers` which takes 2 minutes to download and finish. 

Try to install this module, for example, https://github.com/htruong/aiy-voicebonnet-soundcard-dkms-driver - on a git kernel and a stock kernel. You will see that it's just so much more painful to install this: https://github.com/htruong/snd-i2s_rpi on the Crankshaft image that has a git kernel vs image that has a stock kernel. 

I would say it wouldn't matter to the developer when we need to do it in the development image. To us, having to wait an hour more to build is ok. To the end user, each of them having to wait an hour more to build every time they want to build one is something we want to avoid if that's possible.

**Comment by htruong** [comment]
I totally understand, the rpi-update thing is fiddly. Sometimes we do it and it will make the whole openauto thing work, sometimes we do it and it breaks it. Thanks to your script though I think we can totally pull off a whole compile-and-make system.

**Comment by hawkeyexp** [comment]
I have removed rpi-update for now

**Comment by htruong** [comment]
Thank you so much @hawkeyexp

**Pull request merged**
