### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by keredson**
proposed `FAQ.md` for #19 and one other question i ran into when first using.

### CODE REVIEW

**Comment by htruong** [comment]
Thanks for helping with the FAQs, I have been wanting to write one for a while.

**Comment by htruong** [comment]
Hello @keredson - I hope you don't mind. I'm trying to consolidate where a user can look up problems and answers. Do you mind that I move the FAQ to the wiki? That way you don't even have to do a pull request, just edit whatever you want right away.

**Comment by keredson** [comment]
I've no objection.  :)

**Comment by htruong** [comment]
Thank you so much :+1:

**Pull request merged**
